(* ::Package:: *)

(* ============================================================ *)
(*                                                              *)
(*   SEISMIC WAVE PROPAGATION ACROSS THE GLOBE                  *)
(*                                                              *)
(*   From First Principles --- Earthquakes, Nuclear Tests,      *)
(*   and Ground Motion Visualization                            *)
(*                                                              *)
(*   Author: Marco Thiel                                        *)
(*   Date:   June 2026                                          *)
(*                                                              *)
(*   A Wolfram Community blog post companion notebook.           *)
(*   This file imports the function library                      *)
(*   SeismicWavePropagation.wl and calls its functions           *)
(*   with explicit arguments to generate all figures,            *)
(*   tables, and animations.                                     *)
(*                                                              *)
(* ============================================================ *)


(* ============================================================ *)
(* INITIALIZATION                                               *)
(* ============================================================ *)

(* Import the function library.                                  *)
(* SeismicWavePropagation.wl must be in the same directory or    *)
(* on $Path. It provides all computational functions:            *)
(*   - PREM velocity model                                       *)
(*   - Ray tracing and travel time computation                   *)
(*   - Earthquake catalog and energy calculations                *)
(*   - Wavefront animation tools                                 *)
(*   - Ground Motion Visualization (GMV) engine                  *)
(*   - Nuclear test discrimination tools                         *)

Get["SeismicWavePropagation.wl"]


(* ============================================================ *)
(* ============================================================ *)
(*                                                              *)
(*   SECTION 1: WHAT IS AN EARTHQUAKE?                          *)
(*                                                              *)
(* ============================================================ *)
(* ============================================================ *)

(* ---- 1.1 Earth's interior structure ----                      *)
(*                                                              *)
(* The Earth is a differentiated body with a layered internal    *)
(* structure, shaped by 4.5 billion years of gravitational       *)
(* separation and radiogenic heating. At the centre lies the     *)
(* inner core, a solid sphere of iron-nickel alloy with a        *)
(* radius of approximately 1221 km. Temperatures there reach     *)
(* ~5200 K, but the immense pressure (over 330 GPa) keeps the   *)
(* iron crystalline. Surrounding it is the outer core, a         *)
(* convecting shell of liquid iron extending to a radius of      *)
(* 3480 km from the centre. This liquid layer is the source of   *)
(* Earth's magnetic field via the geodynamo. Above the core      *)
(* lies the mantle, composed primarily of silicate minerals       *)
(* (olivine, pyroxene, perovskite at depth), extending to a      *)
(* mean radius of 6371 km. The mantle is solid on seismic time   *)
(* scales but flows viscously over geological time, driving the  *)
(* convection currents that move tectonic plates. Finally, the   *)
(* crust is a thin veneer --- just 5-7 km thick beneath the     *)
(* oceans (basaltic) and 30-70 km thick beneath the continents   *)
(* (granitic). It is within and just below this crust that most  *)
(* earthquakes originate.                                        *)
(*                                                              *)
(* ---- 1.2 Plate tectonics and strain accumulation ----         *)
(*                                                              *)
(* Earth's surface is divided into approximately 15 major        *)
(* lithospheric plates and numerous smaller ones. These rigid     *)
(* plates --- comprising the crust and the uppermost mantle      *)
(* (the lithosphere) --- float atop the partially molten         *)
(* asthenosphere. Driven by mantle convection, slab pull at      *)
(* subduction zones, and ridge push at mid-ocean ridges, the     *)
(* plates move at rates of 2 to 10 cm per year. While this may   *)
(* seem negligible, over decades to centuries the cumulative     *)
(* displacement across plate boundaries amounts to metres of     *)
(* strain stored as elastic deformation in the surrounding rock. *)
(*                                                              *)
(* At convergent boundaries (subduction zones and continental    *)
(* collision zones), plates are thrust together --- producing    *)
(* the world's largest earthquakes (e.g. M9.5 Chile 1960,       *)
(* M9.1 Tohoku 2011). At transform boundaries (e.g. the San     *)
(* Andreas Fault), plates slide past one another. At divergent   *)
(* boundaries (mid-ocean ridges), plates pull apart. Each        *)
(* boundary type produces characteristic seismicity patterns     *)
(* and focal mechanisms.                                         *)
(*                                                              *)
(* ---- 1.3 Elastic rebound theory ----                          *)
(*                                                              *)
(* The physical mechanism of earthquakes was first clearly       *)
(* articulated by H. F. Reid in 1910, following his study of    *)
(* the 1906 San Francisco earthquake on the San Andreas Fault.  *)
(* Reid's "elastic rebound theory" states: rock on either side   *)
(* of a locked fault deforms elastically under tectonic stress   *)
(* until the accumulated shear stress exceeds the frictional     *)
(* strength of the fault surface. At that point, the fault       *)
(* ruptures suddenly, and the rock on each side snaps back       *)
(* ("rebounds") to an undeformed state. The elastic strain       *)
(* energy stored over decades is released in seconds as seismic  *)
(* waves that radiate outward from the rupture zone.             *)
(*                                                              *)
(* ---- 1.4 Quantifying earthquakes ----                         *)
(*                                                              *)
(* The size of an earthquake is quantified by the seismic        *)
(* moment, a physical measure of the total deformation:          *)
(*                                                              *)
(*   Seismic Moment:                                             *)
(*     M0 = mu * A * d                                           *)
(*                                                              *)
(*   where:                                                      *)
(*     mu = shear modulus of the rock [Pa]                       *)
(*          (typically ~30 GPa for crustal rock,                 *)
(*           ~70 GPa for upper mantle)                           *)
(*     A  = area of the fault rupture surface [m^2]              *)
(*     d  = average displacement (slip) across the fault [m]     *)
(*                                                              *)
(*   Moment Magnitude (Kanamori 1977):                           *)
(*     Mw = (2/3)(Log10[M0] - 9.1)     [M0 in N*m]              *)
(*                                                              *)
(*   Energy-Magnitude Relation (Gutenberg & Richter 1956,        *)
(*   refined by Kanamori 1977):                                  *)
(*     Log10[Es] = 1.5 Mw + 4.8        [Es in Joules]           *)
(*                                                              *)
(* The moment magnitude scale is logarithmic: each unit increase *)
(* in Mw corresponds to a factor of 10^1.5 ~ 31.6 increase in  *)
(* radiated seismic energy. Some representative fault dimensions:*)
(*                                                              *)
(*   M6: fault area ~ 20 km x 10 km, slip ~ 0.5 m               *)
(*       (e.g. a moderate damaging earthquake)                   *)
(*   M7: fault area ~ 70 km x 25 km, slip ~ 1 m                 *)
(*       (e.g. 2023 Turkey Mw 7.8)                               *)
(*   M9: fault area ~ 1000 km x 200 km, slip ~ 10 m             *)
(*       (e.g. 2011 Tohoku, 2004 Sumatra)                        *)
(*                                                              *)
(* ---- 1.5 Focal mechanisms ----                                *)
(*                                                              *)
(* The geometry of fault rupture creates a characteristic        *)
(* radiation pattern known as a double-couple source. The first  *)
(* motion of P-waves divides the focal sphere into four          *)
(* quadrants: two compressional (first motion away from the      *)
(* source) and two dilatational (first motion toward the         *)
(* source). When projected onto the lower hemisphere, this       *)
(* produces the familiar "beach ball" diagram used in            *)
(* seismology. The pattern of the beach ball reveals the fault   *)
(* orientation and slip direction.                               *)
(*                                                              *)
(* This double-couple radiation pattern is fundamentally         *)
(* different from an explosion, which radiates energy            *)
(* isotropically (equally in all directions). This difference    *)
(* is the physical basis for discriminating earthquakes from     *)
(* nuclear tests --- a topic we shall return to in Section 9.   *)
(*                                                              *)
(* ---- 1.6 Our earthquake catalog ----                          *)
(*                                                              *)
(* We have assembled a catalog of significant earthquakes        *)
(* spanning the magnitude range M6.0 to M9.5, including         *)
(* the most destructive events in recorded history as well as    *)
(* several nuclear tests for comparison. Let us begin by         *)
(* displaying this catalog and plotting the events on a globe.   *)

(* Display the full earthquake catalog as a formatted table *)
displayCatalog[]

(* Plot all catalog events on an orthographic globe projection *)
plotEventMap[]


(* ============================================================ *)
(* ============================================================ *)
(*                                                              *)
(*   SECTION 2: THE PHYSICS OF SEISMIC WAVES                    *)
(*                                                              *)
(* ============================================================ *)
(* ============================================================ *)

(* ---- 2.1 The equation of motion for a continuum ----          *)
(*                                                              *)
(* We begin from first principles. Consider a small volume       *)
(* element of rock within the Earth. Newton's second law for a   *)
(* continuous elastic medium takes the form:                      *)
(*                                                              *)
(*   rho * D^2 u / Dt^2 = Div[sigma] + f                        *)
(*                                                              *)
(* where:                                                        *)
(*   rho     = mass density [kg/m^3]                             *)
(*   u       = displacement vector field [m]                     *)
(*   sigma   = Cauchy stress tensor [Pa]                         *)
(*   f       = body force density (e.g. gravity) [N/m^3]         *)
(*                                                              *)
(* For seismic wave propagation, we neglect body forces (they    *)
(* produce only static deformation) and focus on the dynamic     *)
(* perturbation about the equilibrium state.                     *)
(*                                                              *)
(* ---- 2.2 Hooke's law for isotropic elastic media ----         *)
(*                                                              *)
(* For a linear, isotropic elastic solid, the stress-strain      *)
(* relation (generalized Hooke's law) is:                        *)
(*                                                              *)
(*   sigma_ij = lambda * delta_ij * epsilon_kk + 2 mu * eps_ij  *)
(*                                                              *)
(* where:                                                        *)
(*   lambda, mu = Lame parameters [Pa]                           *)
(*   delta_ij   = Kronecker delta                                *)
(*   epsilon_ij = (1/2)(du_i/dx_j + du_j/dx_i)  (strain tensor) *)
(*   epsilon_kk = Div[u]  (volumetric strain / dilatation)       *)
(*                                                              *)
(* The Lame parameter mu is the shear modulus (rigidity), and    *)
(* lambda is related to the bulk modulus K by:                   *)
(*   K = lambda + (2/3) mu                                       *)
(*                                                              *)
(* ---- 2.3 The Navier-Cauchy equation ----                      *)
(*                                                              *)
(* Substituting Hooke's law into the equation of motion and      *)
(* using the strain-displacement relation yields the             *)
(* Navier-Cauchy equation for elastic wave propagation:          *)
(*                                                              *)
(*   rho * D^2 u / Dt^2 = (lambda + 2 mu) Grad[Div[u]]         *)
(*                         - mu Curl[Curl[u]]                    *)
(*                                                              *)
(* or equivalently, using the vector identity                    *)
(*   Curl[Curl[u]] = Grad[Div[u]] - Laplacian[u]:               *)
(*                                                              *)
(*   rho * D^2 u / Dt^2 = (lambda + mu) Grad[Div[u]]            *)
(*                         + mu Laplacian[u]                     *)
(*                                                              *)
(* This is a coupled system of PDEs for the three components     *)
(* of displacement. The key insight of seismology is that it     *)
(* can be decoupled using the Helmholtz decomposition.           *)
(*                                                              *)
(* ---- 2.4 Helmholtz decomposition: P- and S-waves ----         *)
(*                                                              *)
(* Any vector field can be decomposed into irrotational and      *)
(* solenoidal parts:                                             *)
(*                                                              *)
(*   u = Grad[phi] + Curl[psi]                                   *)
(*                                                              *)
(* where phi is a scalar potential and psi is a vector           *)
(* potential. Substituting into the Navier-Cauchy equation and   *)
(* separating:                                                   *)
(*                                                              *)
(* P-waves (from phi, the compressional potential):               *)
(*   Laplacian[phi] = (1/alpha^2) * D^2 phi / Dt^2              *)
(*                                                              *)
(*   where alpha = Sqrt[(lambda + 2 mu) / rho]                   *)
(*                                                              *)
(* S-waves (from psi, the shear potential):                       *)
(*   Laplacian[psi] = (1/beta^2) * D^2 psi / Dt^2               *)
(*                                                              *)
(*   where beta = Sqrt[mu / rho]                                 *)
(*                                                              *)
(* These are classical wave equations. The solutions propagate   *)
(* at velocities alpha (P-wave) and beta (S-wave) respectively. *)
(*                                                              *)
(* ---- 2.5 P-wave properties ----                               *)
(*                                                              *)
(* P-waves (primary waves) are compressional: the particle       *)
(* motion is parallel (longitudinal) to the direction of wave    *)
(* propagation. They are the fastest seismic waves and           *)
(* therefore arrive first at any seismometer. Typical values:    *)
(*                                                              *)
(*   In the crust:      alpha ~ 6.0 km/s                        *)
(*   In the upper mantle: alpha ~ 8.0 km/s                      *)
(*   At the core-mantle boundary: alpha ~ 13.7 km/s             *)
(*   In the outer core (liquid): alpha ~ 8.0-10.3 km/s          *)
(*   In the inner core: alpha ~ 11.0-11.3 km/s                  *)
(*                                                              *)
(* P-waves can propagate through both solids and liquids,        *)
(* because compression does not require shear rigidity.          *)
(*                                                              *)
(* ---- 2.6 S-wave properties ----                               *)
(*                                                              *)
(* S-waves (secondary waves) are shear waves: the particle       *)
(* motion is perpendicular (transverse) to the direction of      *)
(* propagation. They are slower than P-waves by a factor that    *)
(* depends on Poisson's ratio:                                   *)
(*                                                              *)
(*   alpha / beta = Sqrt[(lambda + 2 mu) / mu]                   *)
(*                = Sqrt[2(1 - nu) / (1 - 2 nu)]                *)
(*                                                              *)
(* For a Poisson ratio of nu = 0.25 (a common approximation     *)
(* for crustal rock), this gives alpha/beta = Sqrt[3] ~ 1.73.   *)
(*                                                              *)
(* Crucially, S-waves CANNOT propagate in fluids, because the   *)
(* shear modulus mu = 0 in a liquid. This has a profound         *)
(* consequence: S-waves are blocked by the liquid outer core,    *)
(* creating a "shadow zone" for direct S-wave arrivals at        *)
(* epicentral distances between about 104 and 140 degrees.       *)
(* This shadow zone was one of the key pieces of evidence        *)
(* proving the existence of a liquid outer core (Oldham 1906,    *)
(* Gutenberg 1913).                                              *)
(*                                                              *)
(* ---- 2.7 Surface waves ----                                   *)
(*                                                              *)
(* In addition to body waves (P and S), the free surface of      *)
(* the Earth supports surface waves, which are confined to the   *)
(* near-surface region and decay exponentially with depth.       *)
(* There are two types:                                          *)
(*                                                              *)
(* Rayleigh waves (Lord Rayleigh 1885):                          *)
(*   - Retrograde elliptical particle motion in the vertical     *)
(*     plane containing the propagation direction                *)
(*   - Velocity ~ 0.92 beta for a Poisson solid                 *)
(*   - Amplitude decays exponentially with depth, with           *)
(*     significant motion down to about one wavelength           *)
(*   - Exist on any free surface of an elastic half-space        *)
(*                                                              *)
(* Love waves (A. E. H. Love 1911):                              *)
(*   - Transverse horizontal particle motion (SH polarization)  *)
(*   - Require a low-velocity layer over a half-space            *)
(*   - Slightly faster than Rayleigh waves                      *)
(*   - Dispersive: velocity depends on frequency                 *)
(*                                                              *)
(* Surface waves are critically important because:               *)
(*   - Their amplitude decays as 1/Sqrt[r] (geometric spreading *)
(*     on a 2D surface), compared to 1/r for body waves          *)
(*     spreading on a 3D wavefront. This means surface waves    *)
(*     dominate far-field seismograms.                           *)
(*   - They carry most of the energy in large earthquakes        *)
(*   - They cause the majority of earthquake damage              *)
(*   - On a sphere, the geometric spreading factor becomes      *)
(*     1/Sqrt[Sin[Delta]], where Delta is the epicentral         *)
(*     distance in radians. This produces a focusing effect      *)
(*     at the antipodal point (Delta = Pi), where Sin[Delta]    *)
(*     approaches zero and amplitudes are amplified.             *)
(*                                                              *)
(* ---- 2.8 Attenuation ----                                     *)
(*                                                              *)
(* Real seismic waves lose energy as they propagate, due to      *)
(* anelastic absorption (conversion of mechanical energy to      *)
(* heat through internal friction in the rock). This is          *)
(* quantified by the quality factor Q:                           *)
(*                                                              *)
(*   Amplitude ~ Exp[-Pi f t / Q]                                *)
(*                                                              *)
(* where f is frequency and t is travel time. Typical values:    *)
(*   Q_P ~ 300-500 in the mantle                                *)
(*   Q_S ~ 100-200 in the mantle (shear attenuation is higher)  *)
(*   Q ~ 5000+ in the inner core                                *)
(*                                                              *)
(* Low Q means high attenuation. The asthenosphere (the          *)
(* partially molten zone beneath the lithosphere, 80-220 km     *)
(* depth) has particularly low Q values, which is evidence       *)
(* for partial melting there.                                    *)
(*                                                              *)
(* Note: In our PREM-based simulations below, we compute         *)
(* travel times using the velocity model but do not explicitly   *)
(* model attenuation. The synthetic seismograms use Ricker       *)
(* wavelets whose amplitude is determined by the per-station     *)
(* normalization scheme rather than by physical attenuation      *)
(* --- this is a common simplification in Ground Motion          *)
(* Visualizations.                                               *)


(* ============================================================ *)
(* ============================================================ *)
(*                                                              *)
(*   SECTION 3: THE PREM VELOCITY MODEL                         *)
(*                                                              *)
(* ============================================================ *)
(* ============================================================ *)

(* ---- 3.1 Overview of PREM ----                                *)
(*                                                              *)
(* The Preliminary Reference Earth Model (PREM) was published   *)
(* by Dziewonski & Anderson in 1981 and remains the standard    *)
(* 1-D reference model of the Earth's interior. It was           *)
(* constructed by inverting a massive dataset comprising:         *)
(*   - Free oscillation eigenfrequencies (normal modes)          *)
(*   - Surface wave dispersion measurements                      *)
(*   - Body wave travel times from the ISC bulletin              *)
(*   - Astronomical-geodetic constraints (mass, moment of        *)
(*     inertia)                                                  *)
(*                                                              *)
(* PREM specifies density rho(r), P-wave velocity alpha(r),     *)
(* S-wave velocity beta(r), and the quality factors Q_mu(r)     *)
(* and Q_kappa(r) as functions of radius. The model is           *)
(* piecewise-polynomial within each layer, with discontinuities  *)
(* at major boundaries:                                          *)
(*                                                              *)
(*   Inner Core Boundary (ICB): r = 1221.5 km (5150 km depth)   *)
(*   Core-Mantle Boundary (CMB): r = 3480 km (2891 km depth)    *)
(*   670-km discontinuity: r = 5701 km                          *)
(*   400-km discontinuity: r = 5971 km                          *)
(*   Mohorovicic discontinuity: r ~ 6346 km (24.4 km depth)     *)
(*                                                              *)
(* Our implementation tabulates the PREM values and uses         *)
(* Mathematica's Interpolation function within each continuous   *)
(* layer, respecting the discontinuities. This gives smooth      *)
(* velocity profiles that can be evaluated at any radius for     *)
(* the ray tracing calculations in Section 4.                   *)

(* Plot the P-wave and S-wave velocity profiles as functions of depth *)
plotPREMProfiles[]

(* Plot a cross-section of the Earth showing the internal layers *)
(* colored by P-wave velocity *)
plotPREMCrossSection[]


(* ============================================================ *)
(* ============================================================ *)
(*                                                              *)
(*   SECTION 4: RAY THEORY AND TRAVEL TIMES                     *)
(*                                                              *)
(* ============================================================ *)
(* ============================================================ *)

(* ---- 4.1 Snell's law in a spherically symmetric Earth ----    *)
(*                                                              *)
(* In a medium where the velocity varies continuously with       *)
(* depth, seismic waves do not travel in straight lines ---      *)
(* they are refracted. In a spherically symmetric Earth (such    *)
(* as PREM), Snell's law takes the form:                         *)
(*                                                              *)
(*   p = r Sin[i] / v(r) = constant along a ray                 *)
(*                                                              *)
(* where:                                                        *)
(*   p    = ray parameter [s/rad] (conserved quantity)           *)
(*   r    = radial distance from Earth's center [km]             *)
(*   i    = angle of incidence (angle between ray and radial     *)
(*          direction) [rad]                                      *)
(*   v(r) = seismic velocity at radius r [km/s]                  *)
(*                                                              *)
(* The ray parameter p is the seismological analogue of          *)
(* Snell's law in optics. It is conserved along each ray path   *)
(* and uniquely determines the ray geometry.                     *)
(*                                                              *)
(* ---- 4.2 The turning point ----                               *)
(*                                                              *)
(* A ray traveling downward into the Earth encounters increasing *)
(* velocity (in general), which bends the ray back toward the   *)
(* surface. The turning point occurs where the ray becomes       *)
(* horizontal (i = Pi/2), which gives:                           *)
(*                                                              *)
(*   p = r_tp / v(r_tp)                                          *)
(*                                                              *)
(* Defining the slowness function eta(r) = r / v(r), the        *)
(* turning point radius r_tp is the solution of:                 *)
(*                                                              *)
(*   eta(r_tp) = p                                               *)
(*                                                              *)
(* Rays with smaller p (steeper take-off angle) penetrate        *)
(* deeper and emerge at greater epicentral distances.            *)
(*                                                              *)
(* ---- 4.3 Travel time and distance integrals ----              *)
(*                                                              *)
(* For a ray with parameter p traveling from the surface to its  *)
(* turning point and back, the epicentral distance Delta and     *)
(* travel time T are given by the integrals:                     *)
(*                                                              *)
(*   Delta(p) = 2 Integrate[p / (r Sqrt[eta(r)^2 - p^2]),       *)
(*                          {r, r_tp, R}]                        *)
(*                                                              *)
(*   T(p) = 2 Integrate[eta(r)^2 / (r Sqrt[eta(r)^2 - p^2]),   *)
(*                      {r, r_tp, R}]                            *)
(*                                                              *)
(* where R = 6371 km is Earth's radius. These are evaluated      *)
(* numerically using the PREM velocity profile.                  *)
(*                                                              *)
(* A crucial point: these integrals depend ONLY on the velocity  *)
(* model and the ray parameter p --- they are independent of     *)
(* the earthquake magnitude. A M9 megathrust and a M2            *)
(* microearthquake at the same location produce P-waves that     *)
(* arrive at any given station at exactly the same time. The     *)
(* magnitude affects the amplitude and duration of the signal,   *)
(* not the travel time. This universality is what makes          *)
(* seismic travel time tables possible.                          *)

(* Plot travel time curves for P, S, and Rayleigh waves *)
(* as functions of epicentral distance in degrees *)
plotTravelTimeCurves[]

(* Plot ray paths through the Earth's interior, showing how *)
(* rays at different take-off angles sample different depths *)
plotRayPaths[]


(* ============================================================ *)
(* ============================================================ *)
(*                                                              *)
(*   SECTION 5: SEISMIC ENERGY                                  *)
(*                                                              *)
(* ============================================================ *)
(* ============================================================ *)

(* ---- 5.1 The energy-magnitude relation ----                   *)
(*                                                              *)
(* The total seismic energy radiated by an earthquake is         *)
(* related to its moment magnitude by the Gutenberg-Richter-     *)
(* Kanamori relation:                                            *)
(*                                                              *)
(*   Log10[Es] = 1.5 Mw + 4.8        [Es in Joules]             *)
(*                                                              *)
(* This relation reveals the extraordinary range of seismic      *)
(* energy: each unit increase in magnitude corresponds to a      *)
(* factor of 10^1.5 ~ 31.6 increase in energy. Going from       *)
(* M6 to M9 (three magnitude units) means an energy increase    *)
(* of 31.6^3 ~ 31,623 --- over four orders of magnitude.        *)
(*                                                              *)
(* To put these numbers in perspective:                          *)
(*   M6.0:  Es ~ 6.3 x 10^13 J  ~ 15 kilotons TNT              *)
(*   M7.0:  Es ~ 2.0 x 10^15 J  ~ 474 kilotons TNT             *)
(*   M8.0:  Es ~ 6.3 x 10^16 J  ~ 15 megatons TNT              *)
(*   M9.0:  Es ~ 2.0 x 10^18 J  ~ 474 megatons TNT             *)
(*   M9.5:  Es ~ 1.1 x 10^19 J  ~ 2700 megatons TNT            *)
(*          (Chile 1960 --- largest recorded earthquake)         *)
(*                                                              *)
(* The 1960 Chile earthquake released energy equivalent to       *)
(* roughly 2700 megatons of TNT --- about 54,000 times the      *)
(* yield of the Hiroshima bomb (20 kt) and far exceeding the    *)
(* largest nuclear weapon ever detonated (Tsar Bomba, 50 Mt).   *)

(* Display a formatted comparison table of earthquake energies *)
(* alongside nuclear test yields and everyday energy scales *)
displayEnergyComparison[]

(* Plot a bar chart of seismic energy for catalog events *)
(* on a logarithmic scale, color-coded by magnitude *)
plotEnergyBarChart[]


(* ============================================================ *)
(* ============================================================ *)
(*                                                              *)
(*   SECTION 6: GLOBAL WAVEFRONT ANIMATION                      *)
(*                                                              *)
(* ============================================================ *)
(* ============================================================ *)

(* ---- 6.1 Visualizing seismic wavefronts on a globe ----       *)
(*                                                              *)
(* With the PREM velocity model and travel time curves in hand,  *)
(* we can visualize how seismic wavefronts sweep across the      *)
(* globe after an earthquake. At any given time t after the      *)
(* origin, each wave type (P, S, Rayleigh) has reached a        *)
(* specific epicentral distance Delta(t). On a globe, the        *)
(* locus of points at distance Delta from the epicenter forms    *)
(* a small circle --- the wavefront.                             *)
(*                                                              *)
(* Our animation draws:                                          *)
(*   - P-wave wavefront in blue (fastest, arrives first)         *)
(*   - S-wave wavefront in red (arrives second)                  *)
(*   - Rayleigh wave wavefront in orange (slowest but largest)   *)
(*                                                              *)
(* For earthquakes (double-couple sources), all three wavefronts *)
(* are shown. For nuclear tests (isotropic explosive sources),   *)
(* only the P-wave is shown --- explosions generate very weak    *)
(* S-waves and negligible surface waves. This visual difference  *)
(* is itself a powerful discriminant.                            *)
(*                                                              *)
(* The Manipulate below allows interactive exploration of the    *)
(* wavefront propagation for the 2025 Myanmar earthquake.        *)

(* Interactive wavefront animation on an orthographic globe *)
(* for the 2025 Myanmar Mw 7.7 earthquake *)
wavefrontManipulate[]

(* Generate a grid of snapshots at evenly spaced time intervals *)
(* (useful for static display in a blog post) *)
wavefrontSnapshotGrid[300]

(* Regional wavefront animation focused on Europe *)
(* showing the Crete earthquake as seen from a European perspective *)
creteRegionalManipulate[]


(* ============================================================ *)
(* ============================================================ *)
(*                                                              *)
(*   SECTION 7: SUPERSHEAR RUPTURE                              *)
(*                                                              *)
(* ============================================================ *)
(* ============================================================ *)

(* ---- 7.1 Sub-Rayleigh and supershear rupture ----             *)
(*                                                              *)
(* In most earthquakes, the rupture front propagates along the   *)
(* fault at a velocity below the Rayleigh wave speed --- this    *)
(* is called sub-Rayleigh rupture, and typical rupture speeds    *)
(* are 70-90% of the local S-wave velocity, roughly 2.5-3.2     *)
(* km/s in the crust.                                            *)
(*                                                              *)
(* However, theory predicts (Andrews 1976, Burridge 1973) that   *)
(* under certain conditions --- particularly on smooth,          *)
(* straight fault segments with sufficient pre-stress --- the    *)
(* rupture can accelerate through the "forbidden zone" between   *)
(* the Rayleigh and S-wave speeds and enter the supershear      *)
(* regime, where the rupture speed exceeds the S-wave velocity.  *)
(* This has been confirmed observationally in several events:    *)
(*   - 1999 Izmit, Turkey (Mw 7.4)                              *)
(*   - 2001 Kunlun, Tibet (Mw 7.8)                              *)
(*   - 2018 Palu, Indonesia (Mw 7.5)                             *)
(*   - 2025 Myanmar (Mw 7.7)                                    *)
(*                                                              *)
(* ---- 7.2 The Mach cone ----                                   *)
(*                                                              *)
(* When the rupture speed v_rupture exceeds the S-wave speed     *)
(* v_S, the radiated S-waves cannot outrun the rupture front.   *)
(* They pile up along a conical wavefront --- a Mach cone ---    *)
(* exactly analogous to the sonic boom produced by a supersonic  *)
(* aircraft. The half-angle of the Mach cone is:                 *)
(*                                                              *)
(*   Sin[theta_Mach] = v_S / v_rupture                           *)
(*                                                              *)
(* For the 2025 Myanmar earthquake, preliminary analyses         *)
(* suggest a rupture velocity of approximately 5.5 km/s, while  *)
(* the local crustal S-wave speed is about 3.5 km/s. This       *)
(* gives a Mach number of 5.5/3.5 ~ 1.57 and a Mach cone       *)
(* half-angle of about 39.5 degrees.                             *)
(*                                                              *)
(* The practical consequence of supershear rupture is that the   *)
(* Mach cone concentrates seismic energy along a narrow beam,   *)
(* producing unusually intense shaking at locations that lie     *)
(* in its path --- analogous to the focused shock of a sonic     *)
(* boom. This can lead to unexpectedly severe damage at          *)
(* locations far from the epicenter.                             *)

(* Plot the Mach cone geometry for the 2025 Myanmar supershear *)
(* event, showing the Mach angle and wavefront concentration *)
plotMachCone[]


(* ============================================================ *)
(* ============================================================ *)
(*                                                              *)
(*   SECTION 8: NUCLEAR TESTS AS SEISMIC SOURCES                *)
(*                                                              *)
(* ============================================================ *)
(* ============================================================ *)

(* ---- 8.1 The Comprehensive Nuclear-Test-Ban Treaty ----       *)
(*                                                              *)
(* The Comprehensive Nuclear-Test-Ban Treaty (CTBT), opened     *)
(* for signature in 1996, bans all nuclear explosions. Its       *)
(* verification regime relies heavily on seismology: the         *)
(* International Monitoring System (IMS) operates a global       *)
(* network of seismic stations specifically designed to detect   *)
(* and identify clandestine nuclear tests.                       *)
(*                                                              *)
(* Underground nuclear explosions are efficient seismic sources  *)
(* --- even a 1-kiloton device produces a seismic signal         *)
(* equivalent to roughly a M4 earthquake, easily detectable      *)
(* at teleseismic distances by the IMS network.                  *)
(*                                                              *)
(* ---- 8.2 Yield-magnitude scaling ----                         *)
(*                                                              *)
(* The relationship between nuclear yield (Y, in kilotons) and   *)
(* body-wave magnitude (mb) is approximately:                    *)
(*                                                              *)
(*   mb = a + b * Log10[Y]                                       *)
(*                                                              *)
(* with typical values a ~ 4.0, b ~ 0.75 for well-coupled       *)
(* underground explosions. This means:                           *)
(*   1 kt  -> mb ~ 4.0                                          *)
(*   10 kt -> mb ~ 4.75                                          *)
(*   100 kt -> mb ~ 5.5                                          *)
(*   1 Mt  -> mb ~ 6.25                                          *)
(*                                                              *)
(* Cavity decoupling can reduce the observed magnitude by up     *)
(* to ~1.5 units, making small tests harder to detect --- but    *)
(* requires impractically large cavities for yields above a      *)
(* few kilotons.                                                 *)
(*                                                              *)
(* ---- 8.3 Source physics differences ----                      *)
(*                                                              *)
(* The fundamental difference between an earthquake and a        *)
(* nuclear explosion as seismic sources lies in their source     *)
(* mechanism:                                                    *)
(*                                                              *)
(* Earthquake (double-couple / deviatoric source):               *)
(*   - Shear dislocation on a fault plane                        *)
(*   - Radiation pattern has four lobes (two compressional,      *)
(*     two dilatational)                                         *)
(*   - Efficient generation of S-waves and surface waves        *)
(*   - Surface wave magnitude Ms is large relative to mb        *)
(*                                                              *)
(* Nuclear explosion (isotropic source):                          *)
(*   - Sudden expansion of a cavity (point source of pressure)   *)
(*   - Radiation pattern is spherically symmetric --- all        *)
(*     first motions are compressional                           *)
(*   - Very weak S-wave generation (only from interaction with   *)
(*     the free surface and pre-existing structure)              *)
(*   - Surface wave magnitude Ms is small relative to mb        *)

(* Plot the yield-mb scaling relation for underground nuclear tests *)
plotYieldMbRelation[]

(* Display the North Korean nuclear test series with estimated *)
(* yields and observed magnitudes *)
displayNKTestSeries[]

(* Side-by-side wavefront snapshots comparing earthquake vs *)
(* nuclear test radiation patterns *)
plotEarthquakeVsNuclearSnapshots[]


(* ============================================================ *)
(* ============================================================ *)
(*                                                              *)
(*   SECTION 9: EARTHQUAKE vs EXPLOSION DISCRIMINATION          *)
(*                                                              *)
(* ============================================================ *)
(* ============================================================ *)

(* ---- 9.1 The mb-Ms discrimination method ----                 *)
(*                                                              *)
(* The most widely used seismic discriminant between             *)
(* earthquakes and explosions is the mb:Ms criterion. Body-wave  *)
(* magnitude (mb) is measured from short-period P-waves          *)
(* (typically ~1 Hz), while surface-wave magnitude (Ms) is       *)
(* measured from long-period Rayleigh waves (~20 s period).      *)
(*                                                              *)
(* For earthquakes, the efficient generation of surface waves    *)
(* means that Ms is large relative to mb. Empirically:           *)
(*   Earthquakes: Ms ~ 1.15 mb - 0.52  (Marshall & Basham 1972) *)
(*                                                              *)
(* For explosions, the weak surface wave generation means that   *)
(* Ms is systematically lower for the same mb. This creates a   *)
(* clear separation in the mb-Ms plot: earthquakes cluster       *)
(* above the discrimination line, explosions below.              *)
(*                                                              *)
(* ---- 9.2 Why the method works ----                            *)
(*                                                              *)
(* The physical basis is the source mechanism difference:        *)
(*   - Earthquakes (double-couple) efficiently excite Rayleigh   *)
(*     waves because the shear dislocation has a strong          *)
(*     vertical force component                                  *)
(*   - Explosions (isotropic) generate Rayleigh waves only       *)
(*     through secondary mechanisms (spall, tectonic release)    *)
(*     that are much weaker                                      *)
(*                                                              *)
(* The mb:Ms criterion has been successfully applied to          *)
(* identify all confirmed nuclear tests since the 1960s and     *)
(* is a cornerstone of CTBT verification. It was instrumental   *)
(* in confirming the North Korean tests (2006-2017).             *)

(* Plot the mb-Ms discrimination diagram showing clear *)
(* separation between earthquakes and nuclear tests *)
plotMbMsDiscrimination[]

(* Show the contrasting source mechanisms: double-couple *)
(* (earthquake) vs isotropic (explosion) radiation patterns *)
plotSourceMechanisms[]


(* ============================================================ *)
(* ============================================================ *)
(*                                                              *)
(*   SECTION 10: GROUND MOTION VISUALIZATION --- THE HERO       *)
(*                                                              *)
(* ============================================================ *)
(* ============================================================ *)

(* ---- 10.1 What is a Ground Motion Visualization? ----         *)
(*                                                              *)
(* A Ground Motion Visualization (GMV) is a powerful technique   *)
(* for displaying seismic wave propagation as recorded by a      *)
(* network of seismometers. Developed and popularized by         *)
(* IRIS (Incorporated Research Institutions for Seismology,      *)
(* now part of EarthScope), GMVs have become one of the most     *)
(* compelling ways to communicate the physics of seismic waves   *)
(* to both specialists and the general public.                   *)
(*                                                              *)
(* In a GMV, each seismometer station is represented as a        *)
(* colored dot on a map. The color encodes the instantaneous     *)
(* ground displacement:                                          *)
(*   - Red indicates the ground is moving UP                     *)
(*   - Blue indicates the ground is moving DOWN                  *)
(*   - White/neutral indicates no displacement                   *)
(*   - Color intensity indicates amplitude                       *)
(*                                                              *)
(* As seismic waves sweep through the station network, the       *)
(* coherent wavefronts become visible as bands of alternating    *)
(* red and blue that propagate outward from the epicenter.       *)
(* The result is a direct, visceral visualization of the         *)
(* passage of seismic waves through the Earth --- the viewer     *)
(* literally watches the ground shake.                           *)
(*                                                              *)
(* ---- 10.2 How real GMVs are constructed ----                  *)
(*                                                              *)
(* The IRIS/EarthScope pipeline for producing GMVs involves      *)
(* several data processing steps:                                *)
(*                                                              *)
(* 1. Waveform retrieval: Download continuous seismogram data    *)
(*    from all available broadband stations in the region of     *)
(*    interest (typically hundreds to thousands of stations).    *)
(*    The vertical component (BHZ or LHZ channel) is used.       *)
(*                                                              *)
(* 2. Instrument response removal: Each seismometer has its      *)
(*    own frequency response. The instrument response is         *)
(*    deconvolved to convert from raw digital counts to true     *)
(*    ground displacement (in metres).                           *)
(*                                                              *)
(* 3. Bandpass filtering: The data is filtered to isolate the    *)
(*    frequency band of interest. For large earthquakes          *)
(*    (M >= 6.5), the typical IRIS band is 0.002-0.01 Hz         *)
(*    (periods of 100-500 seconds). This long-period band is    *)
(*    chosen because:                                            *)
(*      - It emphasizes the dominant surface waves               *)
(*      - Long-period waves are coherent over large distances    *)
(*      - Noise and local site effects are minimized             *)
(*      - The wavefronts are smooth and visually clear           *)
(*                                                              *)
(* 4. Per-station normalization: Each station's seismogram is    *)
(*    normalized independently to its own peak absolute          *)
(*    amplitude. This is the crucial step that makes GMVs work:  *)
(*    without normalization, stations near the epicenter would   *)
(*    dominate the display (their amplitudes are orders of       *)
(*    magnitude larger than distant stations), and the wave      *)
(*    passage at distant stations would be invisible. After      *)
(*    normalization, every station responds with comparable      *)
(*    visual intensity, making the wavefront coherent across     *)
(*    the entire network.                                        *)
(*                                                              *)
(* 5. Gain amplification: A gain factor (typically 5) is         *)
(*    applied after normalization. This means the color          *)
(*    saturates when the displacement exceeds 1/gain = 20%       *)
(*    of the station's peak amplitude. The gain makes weaker     *)
(*    arrivals (secondary phases, reflections) visible while     *)
(*    the dominant phases saturate to full color.                 *)
(*                                                              *)
(* 6. Color mapping: At each animation timestep, each station    *)
(*    dot is colored based on its normalized, amplified           *)
(*    displacement: the color ranges from saturated blue          *)
(*    (maximum negative displacement) through white (zero)       *)
(*    to saturated red (maximum positive displacement).          *)
(*                                                              *)
(* ---- 10.3 Our synthetic GMV ----                              *)
(*                                                              *)
(* Rather than downloading real waveform data (which would       *)
(* require significant data access and processing               *)
(* infrastructure), we construct a synthetic GMV from first      *)
(* principles. The key ingredients are:                          *)
(*                                                              *)
(* Station network: We generate a synthetic network of           *)
(* approximately 2000 stations distributed across Europe and     *)
(* the Mediterranean, matching the approximate station density   *)
(* of real European seismic networks (ORFEUS, GEOFON, etc.).    *)
(* Stations are placed preferentially on land areas using the    *)
(* GeoPosition framework.                                        *)
(*                                                              *)
(* Travel times: For each station, we compute the P-wave,        *)
(* S-wave, and Rayleigh wave arrival times using our PREM        *)
(* velocity model and the travel time curves derived in          *)
(* Section 4. The epicentral distance to each station is         *)
(* computed from the great-circle distance using the geodesic    *)
(* formula.                                                      *)
(*                                                              *)
(* Synthetic seismogram: At each station, we construct a         *)
(* synthetic ground displacement trace as the superposition of   *)
(* Ricker wavelets centered at the predicted arrival time of     *)
(* each phase (P, S, Rayleigh).                                  *)
(*                                                              *)
(* ---- 10.4 The Ricker wavelet ----                             *)
(*                                                              *)
(* The Ricker wavelet (also known as the "Mexican hat" wavelet)  *)
(* is a zero-phase wavelet widely used in exploration            *)
(* seismology and synthetic seismogram construction. It is the   *)
(* negative normalized second derivative of a Gaussian:          *)
(*                                                              *)
(*   psi(t) = (1 - 2 (Pi f0 t)^2) Exp[-(Pi f0 t)^2]            *)
(*                                                              *)
(* where f0 is the dominant (peak) frequency. Key properties:    *)
(*                                                              *)
(*   - Clean bipolar pulse: one central positive peak flanked    *)
(*     by two symmetric negative troughs                         *)
(*   - Zero mean (the wavelet integrates to zero)                *)
(*   - Compact support in both time and frequency domains        *)
(*   - The dominant frequency f0 controls the wavelet width:     *)
(*     larger f0 gives a narrower, higher-frequency pulse        *)
(*   - Peak frequency equals f0; bandwidth ~ f0                  *)
(*                                                              *)
(* We chose the Ricker wavelet over a simple sine burst or       *)
(* Gaussian pulse because:                                       *)
(*   - Its bipolar nature naturally produces the alternating     *)
(*     red-blue pattern characteristic of real GMVs              *)
(*   - It is finite-duration (unlike a sinusoid), avoiding       *)
(*     Moire artifacts from sustained oscillations               *)
(*   - It has a well-defined dominant frequency, allowing us     *)
(*     to match the IRIS filter band                             *)
(*                                                              *)
(* We use different dominant frequencies for each seismic phase, *)
(* reflecting their different frequency content:                  *)
(*                                                              *)
(*   P-wave:    f0 = 0.007 Hz  (dominant period ~ 143 s)         *)
(*   S-wave:    f0 = 0.005 Hz  (dominant period ~ 200 s)         *)
(*   Rayleigh:  f0 = 0.003 Hz  (dominant period ~ 333 s)         *)
(*                                                              *)
(* These frequencies fall within the IRIS long-period filter      *)
(* band (0.002-0.01 Hz) used for M >= 6.5 earthquakes, ensuring *)
(* that our synthetic GMV has a realistic visual appearance.      *)
(*                                                              *)
(* ---- 10.5 Per-station normalization ----                      *)
(*                                                              *)
(* Following the IRIS methodology, we normalize each station's   *)
(* synthetic seismogram independently to its own peak absolute   *)
(* amplitude:                                                    *)
(*                                                              *)
(*   u_norm(t) = gain * u(t) / Max[Abs[u(t)]]                   *)
(*                                                              *)
(* where gain = 5 (the IRIS standard). After normalization:      *)
(*                                                              *)
(*   - Every station's peak displacement maps to the same color  *)
(*     intensity, regardless of distance from the epicenter      *)
(*   - The gain factor of 5 means the color saturates at         *)
(*     1/5 = 20% of peak amplitude                               *)
(*   - This makes weaker arrivals clearly visible: P-waves       *)
(*     typically saturate even though they are much weaker than  *)
(*     the Rayleigh wave that dominates the raw trace            *)
(*   - The result is a display where P, S, and Rayleigh wave     *)
(*     fronts are all visible as they sweep across the network   *)
(*                                                              *)
(* This normalization is the key to why GMVs are so effective    *)
(* as visualizations: it compensates for geometric spreading     *)
(* and makes the wave passage visible across the entire          *)
(* network extent.                                               *)
(*                                                              *)
(* ---- 10.6 Generating the GMV ----                             *)
(*                                                              *)
(* We now generate the Ground Motion Visualization for the       *)
(* 2025 Myanmar Mw 7.7 earthquake, as observed across a         *)
(* synthetic European station network. The earthquake            *)
(* epicenter is at 21.88 N, 96.01 E. The P-wave arrives at      *)
(* European stations after approximately 600-900 seconds, with   *)
(* the S-wave following ~400 seconds later and the Rayleigh      *)
(* wave arriving last.                                           *)
(*                                                              *)
(* This is the culmination of everything we have built in this   *)
(* notebook: the PREM velocity model determines the wave         *)
(* speeds, the ray theory gives the travel times, the Ricker     *)
(* wavelet shapes the pulse, and the per-station normalization   *)
(* makes it all visible. The result is a simulation that         *)
(* closely resembles the real IRIS GMVs --- built entirely       *)
(* from first principles.                                        *)

(* Generate the European station network *)
(* ~2000 stations distributed across Europe, Mediterranean, *)
(* and western Asia, preferentially on land *)
stations = generateEuropeanStations[2000];

(* Define the time array for the simulation *)
(* From 250 s to 2800 s in steps of 3.4 s -> ~750 frames *)
tArray = Range[250, 2800, 3.4];

(* Myanmar earthquake epicenter coordinates *)
(* (epicenterLat = 21.88, epicenterLon = 96.01) *)

(* Compute synthetic seismograms for all stations *)
(* Each seismogram is the superposition of Ricker wavelets *)
(* for P, S, and Rayleigh arrivals at the appropriate travel times *)
(* NOTE: This computation takes several minutes for ~2000 stations *)
seismograms = Table[
  syntheticSeismogramGMV[
    geodesicDistanceDeg[21.88, 96.01, stations[[i, 1]], stations[[i, 2]]],
    tArray
  ],
  {i, Length[stations]}
];

(* Per-station normalization with IRIS gain factor = 5 *)
(* Each station's trace is divided by its own peak absolute *)
(* amplitude, then multiplied by the gain *)
normalizedSeis = normalizePerStation[seismograms, 5];

(* Find a reference station at approximately 55 degrees epicentral *)
(* distance --- this station's seismogram will be plotted in the *)
(* lower panel of the GMV display *)
distances = Table[
  geodesicDistanceDeg[21.88, 96.01, stations[[i, 1]], stations[[i, 2]]],
  {i, Length[stations]}
];
refIdx = First[Ordering[Abs[distances - 55], 1]];

(* Interactive Ground Motion Visualization *)
(* The Manipulate slider controls the elapsed time since the *)
(* earthquake origin. The map shows station colors encoding *)
(* instantaneous ground displacement. Below the map, the *)
(* reference station seismogram is displayed with a time marker. *)
Manipulate[
  gmvFrame[t, stations, normalizedSeis, tArray,
    earthquakeCatalog[[1]], refIdx],
  {{t, 250, "Time after origin (s)"}, 250, 2800, 1,
    Appearance -> "Labeled", AnimationRate -> 3}
]

(* ---- 10.7 Exporting the GMV as video ----                     *)
(*                                                              *)
(* To export the GMV as an MP4 video, uncomment the block below.*)
(* WARNING: This takes several hours due to the high cost of     *)
(* rendering ~750 GeoGraphics frames. On a modern desktop,       *)
(* expect 5-10 seconds per frame.                                *)

(*
gmvFrames = Table[
  gmvFrame[t, stations, normalizedSeis, tArray,
    earthquakeCatalog[[1]], refIdx],
  {t, 250, 2800, 3.4}
];
Export["SeismicGMV.mp4", gmvFrames, "FrameRate" -> 30]
*)


(* ============================================================ *)
(* ============================================================ *)
(*                                                              *)
(*   SECTION 11: MODEL VERIFICATION                             *)
(*                                                              *)
(* ============================================================ *)
(* ============================================================ *)

(* ---- 11.1 Comparison with standard travel time tables ----    *)
(*                                                              *)
(* To verify the accuracy of our PREM-based travel time          *)
(* calculations, we compare our computed P-wave and S-wave       *)
(* travel times against the standard reference tables. The       *)
(* primary comparison is with the IASP91 model (Kennett &        *)
(* Engdahl 1991), which is the standard model used by the        *)
(* International Seismological Centre (ISC) for routine          *)
(* earthquake location.                                          *)
(*                                                              *)
(* Our computed travel times agree with the IASP91 tables to     *)
(* within a few seconds across the full distance range 0-180     *)
(* degrees. The residuals are within the natural variability     *)
(* caused by 3-D lateral heterogeneity in the real Earth.        *)

(* Display a verification table comparing our computed travel *)
(* times with IASP91 reference values at standard distances *)
displayVerificationTable[]

(* Display predicted arrival times at major world cities *)
(* for the 2025 Myanmar earthquake *)
displayCityArrivalTimes[]


(* ============================================================ *)
(* ============================================================ *)
(*                                                              *)
(*   SECTION 12: CONCLUSIONS                                    *)
(*                                                              *)
(* ============================================================ *)
(* ============================================================ *)

(* ---- 12.1 Summary ----                                        *)
(*                                                              *)
(* In this notebook, we have built a complete seismic wave       *)
(* propagation simulation framework from first principles,       *)
(* using only the Wolfram Language and fundamental physics.       *)
(*                                                              *)
(* Starting from the Navier-Cauchy equation for elastic wave     *)
(* propagation, we derived the P-wave and S-wave equations,      *)
(* implemented the PREM velocity model (Dziewonski & Anderson    *)
(* 1981), and computed seismic ray paths and travel times via    *)
(* numerical integration of the ray equations in spherical       *)
(* coordinates.                                                  *)
(*                                                              *)
(* We explored the energetics of earthquakes and nuclear tests,  *)
(* visualized seismic wavefronts sweeping across the globe,      *)
(* and examined the physics of supershear rupture. We showed     *)
(* how seismic methods can discriminate between earthquakes      *)
(* and underground nuclear explosions using the mb-Ms criterion, *)
(* which exploits the fundamental difference between double-     *)
(* couple (shear) and isotropic (explosive) source mechanisms.   *)
(*                                                              *)
(* The climax of the notebook is the Ground Motion               *)
(* Visualization (GMV), which synthesizes everything: the PREM   *)
(* velocity model determines wave speeds, ray theory gives       *)
(* travel times, Ricker wavelets shape the synthetic pulses,     *)
(* and per-station normalization (following the IRIS/EarthScope  *)
(* methodology) makes the wave passage visible across the        *)
(* entire station network. The result is a simulation that       *)
(* closely mirrors real GMVs --- built entirely from the         *)
(* equations of elastodynamics.                                  *)
(*                                                              *)
(* All code is available in the companion library file           *)
(* SeismicWavePropagation.wl.                                    *)
(*                                                              *)
(* ---- 12.2 References ----                                     *)
(*                                                              *)
(* Andrews, D. J. (1976). Rupture velocity of plane strain       *)
(*   shear cracks. J. Geophys. Res. 81(32), 5679-5687.          *)
(*                                                              *)
(* Burridge, R. (1973). Admissible speeds for plane-strain       *)
(*   self-similar shear cracks with friction but lacking         *)
(*   cohesion. Geophys. J. Roy. Astr. Soc. 35, 439-455.         *)
(*                                                              *)
(* Dziewonski, A. M., & Anderson, D. L. (1981). Preliminary     *)
(*   reference Earth model. Phys. Earth Planet. Int. 25,         *)
(*   297-356.                                                    *)
(*                                                              *)
(* Gutenberg, B. (1913). Uber die Konstitution des              *)
(*   Erdinnern, erschlossen aus Erdbebenbeobachtungen.           *)
(*   Physikalische Zeitschrift 14, 1217-1218.                    *)
(*                                                              *)
(* Gutenberg, B., & Richter, C. F. (1956). Magnitude and        *)
(*   energy of earthquakes. Annali di Geofisica 9, 1-15.         *)
(*                                                              *)
(* Kanamori, H. (1977). The energy release in great              *)
(*   earthquakes. J. Geophys. Res. 82(20), 2981-2987.            *)
(*                                                              *)
(* Kennett, B. L. N., & Engdahl, E. R. (1991). Traveltimes      *)
(*   for global earthquake location and phase identification.    *)
(*   Geophys. J. Int. 105, 429-465.                              *)
(*                                                              *)
(* Love, A. E. H. (1911). Some Problems of Geodynamics.         *)
(*   Cambridge University Press.                                 *)
(*                                                              *)
(* Marshall, P. D., & Basham, P. W. (1972). Discrimination      *)
(*   between earthquakes and underground explosions employing    *)
(*   an improved Ms scale. Geophys. J. Roy. Astr. Soc. 28,      *)
(*   431-458.                                                    *)
(*                                                              *)
(* Oldham, R. D. (1906). The constitution of the interior of     *)
(*   the Earth, as revealed by earthquakes. Quart. J. Geol.      *)
(*   Soc. London 62, 456-475.                                    *)
(*                                                              *)
(* Rayleigh, Lord (1885). On waves propagated along the plane    *)
(*   surface of an elastic solid. Proc. London Math. Soc.        *)
(*   s1-17, 4-11.                                                *)
(*                                                              *)
(* Reid, H. F. (1910). The Mechanics of the Earthquake. In      *)
(*   The California Earthquake of April 18, 1906, Report of     *)
(*   the State Earthquake Investigation Commission, Vol. 2.      *)
(*   Carnegie Institution of Washington.                         *)
(*                                                              *)
(* Shearer, P. M. (2009). Introduction to Seismology, 2nd ed.   *)
(*   Cambridge University Press.                                 *)
(*                                                              *)
(* Stein, S., & Wysession, M. (2003). An Introduction to        *)
(*   Seismology, Earthquakes, and Earth Structure. Blackwell.    *)
(*                                                              *)
(* ============================================================ *)
(* END OF NOTEBOOK                                               *)
(* ============================================================ *)
